source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExpandableTransition_Example', :exclusive => true do
  pod 'ExpandableTransition', :path => '../'
end

target 'ExpandableTransition_Tests', :exclusive => true do
  pod 'ExpandableTransition', :path => '../'

  
end
