// Generated by Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UICollectionView;
@protocol SnapShotViewProtocol;

SWIFT_PROTOCOL("_TtP24ExpandableViewTransition26BaseViewControllerProtocol_")
@protocol BaseViewControllerProtocol
- (UICollectionView * __nonnull)transitionCollectionView;
- (id <SnapShotViewProtocol> __nonnull)viewToExpand;
@end

@class UIView;

SWIFT_PROTOCOL("_TtP24ExpandableViewTransition33DestinationViewControllerProtocol_")
@protocol DestinationViewControllerProtocol
@optional
- (void)snapShotWillTransition:(UIView * __nonnull)snapShot;
- (void)snapShotTransitioning:(UIView * __nonnull)snapShot;
- (void)snapShotDidTransition:(UIView * __nonnull)snapShot;
- (void)snapShotWillFold:(UIView * __nonnull)snapShot;
- (void)snapShotFoldind:(UIView * __nonnull)snapShot;
- (void)snapShotDidFold:(UIView * __nonnull)snapShot;
@end

@class UINavigationController;
@class UIViewController;
@protocol UIViewControllerAnimatedTransitioning;

SWIFT_CLASS("_TtC24ExpandableViewTransition28NavigationControllerDelegate")
@interface NavigationControllerDelegate : NSObject <UINavigationControllerDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithIsHideExpandedView:(BOOL)isHideExpandedView OBJC_DESIGNATED_INITIALIZER;
- (id <UIViewControllerAnimatedTransitioning> __nullable)navigationController:(UINavigationController * __nonnull)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController * __nonnull)fromVC toViewController:(UIViewController * __nonnull)toVC;
@end


SWIFT_PROTOCOL("_TtP24ExpandableViewTransition20SnapShotViewProtocol_")
@protocol SnapShotViewProtocol
- (UIView * __nonnull)snapShotForTransition;
@end

@protocol UIViewControllerContextTransitioning;

SWIFT_CLASS("_TtC24ExpandableViewTransition10Transition")
@interface Transition : NSObject <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (void)expandCard:(UIViewController * __nonnull)fromViewController toViewController:(UIViewController * __nonnull)toViewController containerView:(UIView * __nonnull)containerView completion:(void (^ __nonnull)(void))completion;
- (void)hideCard:(UIViewController * __nonnull)fromViewController toViewController:(UIViewController * __nonnull)toViewController containerView:(UIView * __nonnull)containerView completion:(void (^ __nonnull)(void))completion;
@end


@interface UIView (SWIFT_EXTENSION(ExpandableViewTransition))
@end

#pragma clang diagnostic pop
